### ISSUE TITLE
Maison: Ajouter signalisation bal vide

### ISSUE THREAD

**Issue by laurenthbp** [HBproptech/Leads2Keys#100]
La zone action / projet est un champ rectangle sans label
Dupliquer la zone Timeline Action / Projet idem immeuble 
![c7c5101c-7d17-4376-9dbc-794ce0155f1f](https://user-images.githubusercontent.com/44204534/49482269-c3aed880-f82e-11e8-84ef-43fb1562438d.png)
![56b118a2-bb01-4b3a-8b4b-f2007b890065](https://user-images.githubusercontent.com/44204534/49482271-c3aed880-f82e-11e8-8285-715bfc4125cb.png)

**Comment by laurenthbp** [comment]
![801a028a-3eb9-4730-a397-ce86d653caf3](https://user-images.githubusercontent.com/44204534/49482392-4172e400-f82f-11e8-85e1-fd974cde4971.jpeg)

**Comment by renanyoy** [comment]
c'est la zone personnes + action/projet comme sur les escaliers

![screen shot 2018-12-05 at 02 50 30](https://user-images.githubusercontent.com/259671/49484817-a979f800-f838-11e8-8189-68987fa02591.png)
