### ISSUE TITLE
Clavier Iphone

### ISSUE THREAD

**Issue by Patrick-hb** [HBproptech/Leads2Keys#105]
J'ai une copine qui utilise un clavier avec emoji et quand elle place le curseur dans les cas avec chiffre genre etage, surface elle a ce clavier par defaut

**Comment by Patrick-hb** [comment]
![silvine](https://user-images.githubusercontent.com/44114817/49596275-41cbc600-f97a-11e8-955b-6e805671d2eb.jpg)

**Comment by renanyoy** [comment]
je vait mettre le clavier normal tout le temps, les autres fonctionnent mal en fait...
