### ISSUE TITLE
URGENT BUG NAVIGATION BLOQUANT SUR IMMEUBLE 

### ISSUE THREAD

**Issue by laurenthbp** [HBproptech/Leads2Keys#111]
Depuis l’apparition des synthèse en Header immeuble, le bouton annuler ne fonctionne plus. Idem sur tous les écrans sous immeuble, escalier ... puisque le bouton Annuler reste dans le Header alors que les zones de saisie immeuble, escalier ... sont plus basses dans le scroll
Obliger de sauvegarder en cas d’erreur de saisie sinon sortie impossible 
![c844a03c-d95c-42f7-ba63-91599daee6da](https://user-images.githubusercontent.com/44204534/49836734-0ed36900-fda4-11e8-9586-812ae6fb78bc.png)

**Comment by renanyoy** [comment]
ça fonctionne, si j'ajoute un maison ou un immeuble je peut soit le delete, soit annuler, et pareil si je modifie des champs.. faut que me donner quelque chose de plus précis.. liste des actions que tu as fait avant...

**Comment by renanyoy** [comment]
et pareil pour le scroll je ne voit pas de problèmes..

**Comment by laurenthbp** [comment]
Le bug est bien présent voici les captures avec en ex. Immeuble du 137 av Parmentier 10e
1 je vais sur un immeuble déjà créé avec 1 escalier minimum ou +
2 je sélectionne un immeuble puis choisi un escalier
3 une fois sur le sceeen escalier le bouton annuler fait rester sur la page, seul « retour et sauver » fonctionne 
![5f0e7484-8f81-4de1-a386-93d695132a04](https://user-images.githubusercontent.com/44204534/49904567-de0a3700-fe6a-11e8-9bfa-b50362b74ebd.png)
![2a7aacb9-c660-4a92-9c34-2671c41cda5e](https://user-images.githubusercontent.com/44204534/49904569-de0a3700-fe6a-11e8-8ad6-5ea5afc500df.png)
![741d86f5-135a-49f1-8542-c8b8614ca42f](https://user-images.githubusercontent.com/44204534/49904571-de0a3700-fe6a-11e8-9344-534313a64105.png)
![fe900315-c73d-42e5-afc4-93461625a9a2](https://user-images.githubusercontent.com/44204534/49904572-de0a3700-fe6a-11e8-9ec5-a2e86ca79073.png)

**Comment by renanyoy** [comment]
OK, je comprend, ici le bouton annuler ne fait pas sortir de la page.
il fait revenir en arrière dans les modifications.

je vait ajouter que quand on click annuler et qu'on n'a rien modifier on sort de la page
