### ISSUE TITLE
TextField: ajouté (X)  dans tous les champs

### ISSUE THREAD

**Issue by laurenthbp** [HBproptech/Leads2Keys#119]
![1e0b38eb-5e22-48ed-ad5f-fc3714fe4cde](https://user-images.githubusercontent.com/44204534/50034315-8c91b180-fffc-11e8-96fe-14f30bb32eaa.jpeg)
Ajouter une « x » à gauche de « adresse » pour supprimer l’adresse affichée 
Cf. Capture ex. flèche orange 
Systématiser autant que possible cette croix pour supprimer le contenu des zones de saisie en un clic 
![ebcdebe5-a6e5-425e-81e6-ab557804db08](https://user-images.githubusercontent.com/44204534/50034043-5b64b180-fffb-11e8-8e5d-9aa04ba011ce.jpeg)
![c0a70396-a5da-4170-9a43-46487937a877](https://user-images.githubusercontent.com/44204534/50034044-5b64b180-fffb-11e8-9981-8186945d9395.jpeg)

**Comment by laurenthbp** [comment]
![1b7155b0-f291-4fa2-b077-459b5492c2c9](https://user-images.githubusercontent.com/44204534/50034348-a8955300-fffc-11e8-8ff1-a263184e73a9.jpeg)

**Comment by laurenthbp** [comment]
![2a8d1826-2aeb-4ce2-90ac-6e643c1b69f7](https://user-images.githubusercontent.com/44204534/50034380-c6fb4e80-fffc-11e8-95ac-1b47379ca173.jpeg)

**Comment by laurenthbp** [comment]
Mes captures ont bugge upload x 4 :)
Le double click sur back space supprime 2 caractères. Il faut tenir back Space pour effacer toute l’adresse (ou pas compris)

**Comment by renanyoy** [comment]
yep, t'as raison en fait, il me semblait avoir vu le double-click tout effacer d'un coup...

**Comment by laurenthbp** [comment]
Ok
La petite croix cerclée est un standard iOs je pense elle est partout dans ttes les Apps
