### ISSUE TITLE
Personne morale (status entreprise)

### ISSUE THREAD

**Issue by laurenthbp** [HBproptech/Leads2Keys#2]
Ajouter la notion de personne morale (Sté) 
dans la listbox, ajouter Sci / Sarl / Sas / Autre sté, et un champ siège social dans le cas de sté

**Comment by laurenthbp** [comment]
Nous avons l'icône travaux pour la copro. 
Ajouter une icône travaux pour le bien

**Comment by laurenthbp** [comment]
Dans la ListBox "Travaux Copro", ajouter l'item "travaux terminés"

**Comment by laurenthbp** [comment]
Ajout d'item dans "actions & projets" origine du lead 
Cercle d'influence
Ancien client(e)
Relation perso
Acquéreur-vendeur
Recommandé par client

**Comment by laurenthbp** [comment]
Dans l'action "Boitage", prévoir possibilité d'ajouter les informations relatives au Flyer distribué, nom de la campagne, type de campagne, nationale / locale, et pouvoir insérer la photo du Flyer

**Comment by renanyoy** [comment]
il faut pas tout mélanger ensemble, il faut que tu créer une issue pour chaques cas

**Comment by renanyoy** [comment]
le champs "type" dans entreprise, c'est ça déjà, sauf que c'est en edition libre

**Comment by renanyoy** [comment]
là si la société est domicilié à une adresse, c'est que sont siège social est justement à cette adresse

**Comment by renanyoy** [comment]
en fait j'ai ajouté, pour l'instant c'est saisie libre
