### ISSUE TITLE
A supp test de pab

### ISSUE THREAD

**Issue by Patrick-hb** [HBproptech/Leads2Keys#21]
Je cherche les tag genre bug
Et insérer une image depuis la version mobile

**Comment by Patrick-hb** [comment]
J'ai l'impression que les tag c est Renan qui gère dans son profil

**Comment by Patrick-hb** [comment]
Pour l'upload d'image c'est pas sur en version mobile gratuit

**Comment by Patrick-hb** [comment]
J'ai chargé fasthub pour mobile ça a l'air pas mal pour UP des infos

**Comment by Patrick-hb** [comment]
~~~~ je ne trouve pas pour les images

**Comment by Patrick-hb** [comment]
![](https://i.imgur.com/w3kMvpD.jpg)![Test upload](https://i.imgur.com/yNrkGho.jpg)

**Comment by Patrick-hb** [comment]
Ça marche en bas dans commentaire en faisant glisser le bandeau jusqu'à image et appuyer sur select pour browser en local

**Comment by Patrick-hb** [comment]
![Photo taguée](https://i.imgur.com/dRansfA.jpg)

**Comment by Patrick-hb** [comment]
:muscle::+1:

**Comment by Patrick-hb** [comment]
Donnez moi un retour sur la qualité des post qu'on s'améliore avec le temps

**Comment by renanyoy** [comment]
je clot le post ;)
