### ISSUE TITLE
Test bretagne

### ISSUE THREAD

**Issue by Patrick-hb** [HBproptech/Leads2Keys#22]
Pas de pb

**Comment by renanyoy** [comment]
Oki

**Comment by Patrick-hb** [comment]
![image](https://user-images.githubusercontent.com/44114817/48303803-649bc380-e50f-11e8-8a03-c974e3520606.jpg)

**Comment by Patrick-hb** [comment]
![d1f92516-abf2-4f95-acc7-e427ad055025](https://user-images.githubusercontent.com/44114817/48303819-cb20e180-e50f-11e8-88f0-ef75d4cef5e6.jpeg)
