### ISSUE TITLE
Création d'un événement (VISUEL / LEAD)

### ISSUE THREAD

**Issue by laurenthbp** [HBproptech/Leads2Keys#31]
Arrivée sur un écran de look idem "Création d'un immeuble" avec en entête "Création d'un événement" 
Le type d’événement est sélectionnable via un nuage de tags et comme pour les autres Tags, sera en mode administrable dans le B.O. 
Selon le type d’événement, on appelle les descriptifs (Tags) correspondants : 
1. Événement visuel (afficher les tags correspondants)
2. Lead (afficher les tags correspondants) : exemple information de vente, estimation ... 
ListBox administrable à créer

ZOOMONS sur un écran de création de d'un événement de type LEAD : 
Tags 

Nom vendeur
@
Tél
Origine du lead : tap, notoriété, ancien client, relation perso, délégation. Recommandation, apporteur, partenaire ...
Type bien : maison, appartement, commerce, immeuble
Nb. Pièces :
Nb. M2
Etage : n/n
Adresse
Cp ville
....

**Comment by Patrick-hb** [comment]
Tu as très bien résumé laurent
Merci de penser a ajouter un champs date de relance pour générer une notification.

Et prévoir une roue crantée : 
Gérer la notification : reporter - archiver - enregistrer
