### ISSUE TITLE
Delete immeuble

### ISSUE THREAD

**Issue by Patrick-hb** [HBproptech/Leads2Keys#47]
J’ai pas inadvertance ajouté un immeuble et je ne peux plus faire machine arrière pour mettre une maison c’est balot
![da1517a7-1030-4573-b1f1-fd9063e55d34](https://user-images.githubusercontent.com/44114817/48413860-4caf8400-e749-11e8-9cf1-7f3701cb5248.png)

**Comment by renanyoy** [comment]
- en fait il fallais faire "annuler" après avoir ajouté l'immeuble
- tu peut tjrs ajouter une maison, tu rentre dans l'immeuble et tout en bas tu peut ajouter une maison en plus
mas ok, il va falloir réfléchir à un delete: peut être pendant 5mn après la création

**Comment by renanyoy** [comment]
ou juste si l'immeuble est vide
