### ISSUE TITLE
BO: remplacer prospects par L2K bleu

### ISSUE THREAD

**Issue by Patrick-hb** [HBproptech/Leads2Keys#54]
![a2ds_leads2keys](https://user-images.githubusercontent.com/44114817/48540530-a4213180-e8ba-11e8-92b0-5c34f5b58d16.jpg)

**Comment by laurenthbp** [comment]
Sur le B.O. le logo L2K sera bleu (couleur administrateur / responsables d'entité), ainsi que la charte graphique par la suite.
