### ISSUE TITLE
Autorisation (à tort) de modifier des infos sur une BAL appartenant à un autre user

### ISSUE THREAD

**Issue by laurenthbp** [HBproptech/Leads2Keys#62]
De mémoire, nous avons prévu dans les fonctionnalités la possibilité de créer une info / projet ... hors secteur. En revanche, en testant, j'ai pu modifier les informations, supprimer des tags ... 
Pas normal je pense.

**Comment by renanyoy** [comment]
si c'est normal
les infos places sont partagées par toutes les personnes de l'agence, y'a que les projets qui sont personnels
après c'est le patron d'agence qui décide en assignant les secteurs qui a droit de modifier les infos de tel ou tel secteur

**Comment by renanyoy** [comment]
yep, y'a un problème, on peut edit hors secteur là
