### ISSUE TITLE
app: contraindre le remplissage profile avant de pouvoir faire une demande d'affiliation

### ISSUE THREAD

**Issue by Patrick-hb** [HBproptech/Leads2Keys#64]
dans le sign up le candidat n'inscrit que son identifiant mail et mot de passe donc forcement on a pas le detail de qui demande une affiliation
![leads2keys](https://user-images.githubusercontent.com/44114817/48718298-63f3e300-ec1b-11e8-9635-443f649f2a92.jpg)

peut etre avant d'autoriser la demande d'affiliation il faut obliger de compléter l'etat civil

**Comment by renanyoy** [comment]
ok, mais y'a un message dans le dashboard qui demande de completer le profile avant d'envoyer une demande d'affiliation.
si néamoins il envoit une demande d'affiliation, il suffit de la refuser...

**Comment by renanyoy** [comment]
je vait voir pour contraindre..
