### ISSUE TITLE
Géoloc imprécise lors de création d'un lead ou event (en mode saisie rapide)

### ISSUE THREAD

**Issue by laurenthbp** [HBproptech/Leads2Keys#70]
L'adresse de géoloc dans les screens de saisie rapide LEAD + EVENT n'est pas précise. Ex. Saisie faite au 141 av. Parmentier, l'adresse pré-affichée est le 156 av. Parmentier (légèrement en face en décalé). 
Peut-etre est normal ? ou pas améliorable à ce stade ?

**Comment by renanyoy** [comment]
yep, j'ai rien pour savoir si l'info est bonne ou pas, mais tu peut changer à la main..
sinon tu peut faire annuler et revenir en espérant une géoloc mieux

- sinon, peut être à voir plus tard une liste box avec plusieurs propositions

**Comment by laurenthbp** [comment]
Merci

Ok on laisse comme ça j’étais à l’intérieur de l’agence peut être un pb de réseau. Laissons les tests se faire à grands echelle. 

Cordialement, Laurent Hayoun Directeur d’agence
