### ISSUE TITLE
Menu: agrandir premier niveau, cause: Barre inférieure de menu sur iPhone X

### ISSUE THREAD

**Issue by laurenthbp** [HBproptech/Leads2Keys#74]
Le texte des icônes est tronqué par la barre spécifique à la navigation swipe sur iPhone X. Remonter la barre de quelques millimètres
Merci

**Comment by laurenthbp** [comment]
![5a6254d8-1ece-4c81-a157-4c3945a41f87](https://user-images.githubusercontent.com/44204534/49046287-d80e2800-f1d3-11e8-9908-2be793908939.png)

**Comment by renanyoy** [comment]
la barre est placé l'os, pas par les applications..
