### ISSUE TITLE
alerte email: création de compte

### ISSUE THREAD

**Issue by Patrick-hb** [HBproptech/Leads2Keys#82]
Pour chaque nouvelle création de compte de test et après les test envoyer un mail sur testl2k@hbproptech.com
Merci

**Comment by renanyoy** [comment]
normalement c'est bon là, j'ai mis à l'affectation en fait pour avoir une profil remplis..

**Comment by Patrick-hb** [comment]
Dans ce cas je ne peux pas savoir si un patron ouvre un compte agence ?
