### ISSUE TITLE
Accès dans GitHub à des projets extérieurs à L2K !!!

### ISSUE THREAD

**Issue by laurenthbp** [HBproptech/Leads2Keys#86]
J'ai saisi "boite à lettre" dans la search barre et j'ai récupéré des issues qui n'appartiennent pas à notre projet ...

**Comment by renanyoy** [comment]
yep, c'est pas moi qui maintient github ;)

**Comment by renanyoy** [comment]
il faut tapper dans filter issues, pas dans le search générale de github
