### ISSUE TITLE
ASAP réactivation du bouton "ajouter plusieurs boites à lettre"

### ISSUE THREAD

**Issue by laurenthbp** [HBproptech/Leads2Keys#87]
Le bouton existe mais est inactif (ça fonctionnait avant)

**Comment by renanyoy** [comment]
yep, je savait pas comment l'implémenter, je vait ajouter

**Comment by renanyoy** [comment]
yep, je suis un peu décallé, en mm temps c'est pratique pour dev sans pertuber les testeurs ;)

**Comment by laurenthbp** [comment]
C'est sur :)
Pas d'urgence, pour les copros où il y a + 50 BALs, tu pourras **plus tard (pas urgent)** proposer comme avant une saisie du nombre de Bals, pour éviter une liste box interminable pour les tours de 30 étage avec 500 logements.
